version: '2.1'
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=maryanne
      - POSTGRES_DB=bucket
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
    
  frontend:
    image: bucketlist_frontend
    ports:
    - "4200:4200"

  backend:
    image: bucketlist_backend
    ports:
    - "5000:5000"
    env_file:
    - ./.env
    depends_on:
      database:
        condition: service_healthy